title: "Mal's GitHub Pages Site"
description: "Mal's GitHub web pages."
repository_url: https://github.com/mal-votes/mal-votes.github.io/
permalink: pretty
plugins:
  - jekyll-redirect-from
  - jemoji
