title: "Mal's Voting Guide"
description: "Mal's voting guides hosted on GitHub web pages."
repository_url: https://github.com/mal-votes/mal-votes.github.io/
permalink: pretty
plugins:
  - jekyll-redirect-from
